In [3]:
import numpy as np

#### 1 D array

In [4]:
arr1= np.array([1,2,3,4,5,6])

In [5]:
arr1

array([1, 2, 3, 4, 5, 6])

In [6]:
type(arr1)
arr1.shape

(6,)

In [7]:
arr1=arr1.reshape((2,3))

In [8]:
arr1.shape

(2, 3)

In [9]:
idnarr=np.eye(3)

In [10]:
idnarr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
arr1.dtype

dtype('int64')

In [12]:
arr1=np.array([1,2,3])
arr2=np.array([5,10,20])

In [13]:
arr1*arr2

array([ 5, 20, 60])

In [14]:
arr= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
print(arr[0])
print(arr[0,0])

[1 2 3 4]
1


In [16]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [17]:
arr[0:2,2:]

array([[3, 4],
       [7, 8]])

In [18]:
arrx=arr
arrx

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
arrx[0:,0:]=100

In [20]:
arrx

array([[100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

## Statistical concepts -Normilization
to have a mean of zero (0) and a standerd deviation of 1

In [21]:
data= np.array([1,2,3,4,5])

mean=np.mean(data)
std_dev= np.std(data)

In [22]:
normalized_data= (data-mean)/std_dev
print('Normalized data: ', normalized_data)

Normalized data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [23]:
median=np.median(data)
print(median)
variance=np.var(data)
print(variance)

3.0
2.0


In [24]:
#Lgical operations
data=np.array([1,2,3,4,5,6,7,8,9,10])
data>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [25]:
data[data>5]

array([ 6,  7,  8,  9, 10])

In [26]:
data[(data>4) & (data<8)]

array([5, 6, 7])

In [27]:
import pandas as pd

### Series

In [28]:
series= pd.Series(data)

In [29]:
print(series)

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64


In [30]:
# series from deictonary
data_d={'a':1,'b':2,'c':3,'d':4}
series_dict=pd.Series(data_d)
series_dict

a    1
b    2
c    3
d    4
dtype: int64

In [31]:
data=[10,23,32]
index=['a','b','c']
pd.Series(data, index=index)

a    10
b    23
c    32
dtype: int64

## Dataframe

In [32]:
# creating a dataframe a dictonary of lists
data={
  'Name':['Aman', 'Raman', 'Kaman'],
  'Age':[33,23,46],
  'Location':['CCU', 'Delhi','NYC']
}
df=pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age Location
0   Aman   33      CCU
1  Raman   23    Delhi
2  Kaman   46      NYC
<class 'pandas.core.frame.DataFrame'>


In [96]:
data=[
  {"Name":'Anda', 'Age':34,"Loc":"KOL"},
  {"Name":'Bdan', 'Age':32,"Loc":"Durgapur"},
  {"Name":'Madu', 'Age':27,"Loc":"KOL"}
]
df=pd.DataFrame(data)

In [34]:
df

Name  Age       Loc
0  Anda   34       KOL
1  Bdan   32  Durgapur
2  Madu   27       KOL

In [35]:
df_csv= pd.read_csv("spotify_data clean.csv")
df_csv.head(5)

track_id                                       track_name  \
0  3EJS5LyekDim1Tf5rBFmZl                    Trippy Mane (ft. Project Pat)   
1  1oQW6G2ZiwMuHqlPpP27DB                                             OMG!   
2  7mdkjzoIYlf1rx9EtBpGmU                                      Hard 2 Find   
3  67rW0Zl7oB3qEpD5YWWE5w  Still Get Like That (ft. Project Pat & Starrah)   
4  15xptTfRBrjsppW0INUZjf                            ride me like a harley   

   track_number  track_popularity  explicit artist_name  artist_popularity  \
0             4                 0      True       Diplo                 77   
1             1                 0      True    Yelawolf                 64   
2             1                 4      True   Riff Raff                 48   
3             8                30      True       Diplo                 77   
4             2                 0      True     Rumelis                 48   

   artist_followers                      artist_genres  \
0           2812821                         moombahton   
1           2363438  country hip hop, southern hip hop   
2            193302                                NaN   
3           2813710                         moombahton   
4              8682                           dark r&b   

                 album_id                           album_name  \
0  5QRFnGnBeMGePBKF2xTz5z                   d00mscrvll, Vol. 1   
1  4SUmmwnv0xTjRcLdjczGg2                                 OMG!   
2  3E3zEAL8gUYWaLYB9L7gbp                          Hard 2 Find   
3  5QRFnGnBeMGePBKF2xTz5z                   d00mscrvll, Vol. 1   
4  06FDIpSHYmZAZoyuYtc7kd  come closer / ride me like a harley   

  album_release_date  album_total_tracks album_type  track_duration_min  
0         2025-10-31                   9      album                1.55  
1         2025-10-31                   1     single                3.07  
2         2025-10-31                   1     single                2.55  
3         2025-10-31                   9      album                1.69  
4         2025-10-30                   2     single                2.39

Accessing data from a dataFrame

In [41]:
df_csv[['track_name','artist_name']].head(20)

track_name            artist_name
0                     Trippy Mane (ft. Project Pat)                  Diplo
1                                              OMG!               Yelawolf
2                                       Hard 2 Find              Riff Raff
3   Still Get Like That (ft. Project Pat & Starrah)                  Diplo
4                             ride me like a harley                Rumelis
5                                             BLEED                 Minzie
6                              Te Procuro na Cidade                 AZERDK
7                                       come closer                Rumelis
8                                  Cupido Vagabundo         Toni dos Anjos
9                                         LET’S GO!               PsychoYP
10                                            Stray  What Matters The Most
11                  PAPARAZZI ARRIVE - English Ver.                    A2O
12                                 Root of all Evil          Daniel Caesar
13                                       Let’s Go!!               Ovi Jozi
14               MELODY - CHENYU & SHIJIE & QUCHANG                    A2O
15                                          My Muse            Leon Thomas
16                              A Real Good Bad One             Joe Hermes
17                              BOSS - English Ver.                    A2O
18                                          Bridges        Scarlett Butler
19                                    Can't Go Back               LEROCQUE

In [47]:
df_csv.columns


Index(['track_id', 'track_name', 'track_number', 'track_popularity',
       'explicit', 'artist_name', 'artist_popularity', 'artist_followers',
       'artist_genres', 'album_id', 'album_name', 'album_release_date',
       'album_total_tracks', 'album_type', 'track_duration_min'],
      dtype='object')

In [48]:
df_csv_ordered=df_csv.sort_values('track_popularity', ascending=False)

In [49]:
df_csv_ordered[['track_name', 'artist_name']].head(20)

track_name        artist_name
457                                             Golden            HUNTR/X
88                                             Opalite       Taylor Swift
101                                   Elizabeth Taylor       Taylor Swift
337                                         Man I Need        Olivia Dean
103                                      Father Figure       Taylor Swift
1134                                BIRDS OF A FEATHER      Billie Eilish
450                                           Soda Pop          Saja Boys
460                                          Your Idol          Saja Boys
93                                   Actually Romantic       Taylor Swift
97                                                Wood       Taylor Swift
79    The Life of a Showgirl (feat. Sabrina Carpenter)       Taylor Swift
458                                      How It’s Done            HUNTR/X
95                                          CANCELLED!       Taylor Swift
96                                           Wi$h Li$t       Taylor Swift
100                                    Eldest Daughter       Taylor Swift
179                               WHERE IS MY HUSBAND!               RAYE
454                                What It Sounds Like            HUNTR/X
8030                                              Iris  The Goo Goo Dolls
1138                                        WILDFLOWER      Billie Eilish
249                                              Tears  Sabrina Carpenter

In [50]:
# data=[
#   {"Name":'Anda', 'Age':34,"Loc":"KOL"},
#   {"Name":'Bdan', 'Age':32,"Loc":"Durgapur"},
#   {"Name":'Madu', 'Age':27,"Loc":"KOL"}
# ]
# df=pd.DataFrame(data)

data

[{'Name': 'Anda', 'Age': 34, 'Loc': 'KOL'},
 {'Name': 'Bdan', 'Age': 32, 'Loc': 'Durgapur'},
 {'Name': 'Madu', 'Age': 27, 'Loc': 'KOL'}]

In [53]:
df['Name']

0    Anda
1    Bdan
2    Madu
Name: Name, dtype: object

In [54]:
df.loc[0]

Name    Anda
Age       34
Loc      KOL
Name: 0, dtype: object

In [55]:
df.iloc[0]

Name    Anda
Age       34
Loc      KOL
Name: 0, dtype: object

In [58]:
print(df_csv_ordered.loc[0])

track_id                     3EJS5LyekDim1Tf5rBFmZl
track_name            Trippy Mane (ft. Project Pat)
track_number                                      4
track_popularity                                  0
explicit                                       True
artist_name                                   Diplo
artist_popularity                                77
artist_followers                            2812821
artist_genres                            moombahton
album_id                     5QRFnGnBeMGePBKF2xTz5z
album_name                       d00mscrvll, Vol. 1
album_release_date                       2025-10-31
album_total_tracks                                9
album_type                                    album
track_duration_min                             1.55
Name: 0, dtype: object


In [59]:
print(df_csv_ordered.iloc[0])

track_id                                         1CPZ5BxNNd0n0nF4Orb9JS
track_name                                                       Golden
track_number                                                          4
track_popularity                                                     99
explicit                                                          False
artist_name                                                     HUNTR/X
artist_popularity                                                    87
artist_followers                                                3551538
artist_genres                                                     k-pop
album_id                                         14JkAa6IiFaOh5s0nMyMU9
album_name            KPop Demon Hunters (Soundtrack from the Netfli...
album_release_date                                           2025-06-20
album_total_tracks                                                   12
album_type                                                      

In [60]:
df_ord=df.sort_values('Age')

In [61]:
df_ord

Name  Age       Loc
2  Madu   27       KOL
1  Bdan   32  Durgapur
0  Anda   34       KOL

In [67]:
df_ord.loc[0]

Name    Anda
Age       34
Loc      KOL
Name: 0, dtype: object

In [71]:
df_ord.iloc[0]

Name    Madu
Age       27
Loc      KOL
Name: 2, dtype: object

### Accessing a specified element

In [78]:
# Accessing a specified element using at
df.at[1,'Age']

np.int64(32)

In [76]:
df_csv_ordered.at[100,'artist_name']

'Taylor Swift'

In [77]:
df_csv_ordered.head(20)

track_id  \
457   1CPZ5BxNNd0n0nF4Orb9JS   
88    3yWuTOYDztXjZxdE2cIRUa   
101   1jgTiNob5cVyXeJ3WgX5bL   
337   1qbmS6ep2hbBRaEZFpn7BX   
103   03bTIHJElXZ0O0jqOQvAbY   
1134  6dOtVTDdiauQNBQEDOtlAB   
450   02sy7FAs8dkDNYsHp4Ul3f   
460   1I37Zz2g3hk9eWxaNkj031   
93    2x3mwb96B6TquRqMtbxUE1   
97    5ylJtmaWPJ33cW3En7WOu0   
79    5eXgqtg3T8Av0m1FUaGHex   
458   3RXUgPNIbUgFxsDWuBQEt6   
95    1appZ3c336FkPvCuywfmrs   
96    2TEQvxxQabwLQMqWMg1qGu   
100   62HoDY1Km6lm47haFpUn9c   
179   55lijDD6OAjLFFUHU9tcDm   
454   5sBDrrtLGbV64QJnEqfjer   
8030  6Qyc6fS4DsZjB2mRW9DsQs   
1138  3QaPy1KgI7nu9FJEQUgn6h   
249   42VUCXerQ5qTr4Qp6PhKo4   

                                            track_name  track_number  \
457                                             Golden             4   
88                                             Opalite             3   
101                                   Elizabeth Taylor             2   
337                                         Man I Need             1   
103                                      Father Figure             4   
1134                                BIRDS OF A FEATHER             4   
450                                           Soda Pop             3   
460                                          Your Idol             7   
93                                   Actually Romantic             7   
97                                                Wood             9   
79    The Life of a Showgirl (feat. Sabrina Carpenter)            12   
458                                      How It’s Done             2   
95                                          CANCELLED!            10   
96                                           Wi$h Li$t             8   
100                                    Eldest Daughter             5   
179                               WHERE IS MY HUSBAND!             1   
454                                What It Sounds Like             9   
8030                                              Iris            11   
1138                                        WILDFLOWER             5   
249                                              Tears             2   

      track_popularity  explicit        artist_name  artist_popularity  \
457                 99     False            HUNTR/X                 87   
88                  97     False       Taylor Swift                100   
101                 95     False       Taylor Swift                100   
337                 95     False        Olivia Dean                 88   
103                 94      True       Taylor Swift                100   
1134                94     False      Billie Eilish                 90   
450                 94     False          Saja Boys                 80   
460                 93     False          Saja Boys                 80   
93                  93      True       Taylor Swift                100   
97                  93      True       Taylor Swift                100   
79                  93      True       Taylor Swift                100   
458                 93     False            HUNTR/X                 87   
95                  93      True       Taylor Swift                100   
96                  93      True       Taylor Swift                100   
100                 92      True       Taylor Swift                100   
179                 92     False               RAYE                 81   
454                 92     False            HUNTR/X                 87   
8030                92     False  The Goo Goo Dolls                 76   
1138                92     False      Billie Eilish                 90   
249                 92     False  Sabrina Carpenter                 91   

      artist_followers                          artist_genres  \
457            3551538                                  k-pop   
88           145443567              country, pop, indie, folk   
101          145489371              country, pop, indie, folk   
337            1499

In [80]:
# Accessing a specified element using iat  (using specific row and column index)
df.iat[2,2]

'KOL'

### Data manupulation using DataFrame

In [85]:
#Adding a column
df['Salary']= [30000,32000,53000]

In [86]:
df

Name  Age       Loc  Salary
0  Anda   34       KOL   30000
1  Bdan   32  Durgapur   32000
2  Madu   27       KOL   53000

In [89]:
#Droping the column
df.drop('Salary', axis=1)

Name  Age       Loc
0  Anda   34       KOL
1  Bdan   32  Durgapur
2  Madu   27       KOL

In [90]:
df

Name  Age       Loc  Salary
0  Anda   34       KOL   30000
1  Bdan   32  Durgapur   32000
2  Madu   27       KOL   53000

In [91]:
df.drop('Salary', axis=1, inplace=True)

In [92]:
df

Name  Age       Loc
0  Anda   34       KOL
1  Bdan   32  Durgapur
2  Madu   27       KOL

In [97]:
df['Age']=df['Age']+1

In [98]:
df

Name  Age       Loc
0  Anda   35       KOL
1  Bdan   33  Durgapur
2  Madu   28       KOL

In [99]:
df.describe

<bound method NDFrame.describe of    Name  Age       Loc
0  Anda   35       KOL
1  Bdan   33  Durgapur
2  Madu   28       KOL>

In [100]:
df_csv.describe()

track_number  track_popularity  artist_popularity  artist_followers  \
count   8582.000000       8582.000000        8582.000000      8.582000e+03   
mean       5.772547         52.356211          69.730016      2.403472e+07   
std        6.052792         23.816076          19.645979      3.803180e+07   
min        1.000000          0.000000           0.000000      0.000000e+00   
25%        1.000000         39.000000          60.000000      4.623200e+05   
50%        4.000000         58.000000          74.000000      6.105547e+06   
75%        9.000000         71.000000          84.000000      2.725255e+07   
max      102.000000         99.000000         100.000000      1.455421e+08   

       album_total_tracks  track_duration_min  
count         8582.000000         8582.000000  
mean            13.789443            3.492805  
std             11.887131            1.057970  
min              1.000000            0.070000  
25%              6.000000            2.880000  
50%             13.000000            3.445000  
75%             17.000000            3.990000  
max            181.000000           13.510000

In [105]:
df_csv['album_total_tracks'].max()

181

In [ ]:
df_csv.loc[df_csv['album_total_tracks'].idxmax()]

track_id                                1116IjCqwjydbV6V0twTEQ
track_name                       The Thunder-Fire Dragon Roars
track_number                                                 1
track_popularity                                            28
explicit                                                 False
artist_name                                 Yasuharu Takanashi
artist_popularity                                           58
artist_followers                                        111922
artist_genres                                anime, soundtrack
album_id                                3ksMU0uVKKlBDqPjmaot0v
album_name            FAIRY TAIL SOUNDTRACK ARCHIVES 2009-2013
album_release_date                                  2022-03-16
album_total_tracks                                         181
album_type                                               album
track_duration_min                                         2.1
Name: 2337, dtype: object